version: '3.8'

volumes:
  postgres-data:

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    build:
      context: .
      dockerfile: DockerfilePgAdmin
    ports:
      - 80:80
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=test@postgresql.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - db
    logging:
      driver: "none"